--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD2
--------------------------------------------------------

  CREATE TABLE "SUZI"."BOARD2" 
   (	"NUM" NUMBER(9,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"PWD" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"SUBJECT" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"IPADDR" VARCHAR2(20 BYTE), 
	"HITCOUNT" NUMBER(9,0), 
	"CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SUZI.BOARD2
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_BOARD2_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUZI"."PK_BOARD2_NUM" ON "SUZI"."BOARD2" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD2
--------------------------------------------------------

  ALTER TABLE "SUZI"."BOARD2" ADD CONSTRAINT "PK_BOARD2_NUM" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SUZI"."BOARD2" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SUZI"."BOARD2" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SUZI"."BOARD2" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "SUZI"."BOARD2" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUZI"."BOARD2" MODIFY ("NUM" NOT NULL ENABLE);
