--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FP_PAY
--------------------------------------------------------

  CREATE TABLE "SUZI"."FP_PAY" 
   (	"NUM" NUMBER(10,0), 
	"MEMP" VARCHAR2(2 BYTE), 
	"DCOUPON" VARCHAR2(2 BYTE), 
	"VIPCPON" VARCHAR2(2 BYTE), 
	"MCOUPON" VARCHAR2(2 BYTE), 
	"SCOUPON" VARCHAR2(2 BYTE), 
	"MGFCARD" VARCHAR2(2 BYTE), 
	"BOOKGIFT" VARCHAR2(2 BYTE), 
	"CULTGIFT" VARCHAR2(2 BYTE), 
	"PAYSGIFT" VARCHAR2(2 BYTE), 
	"FRIENDS" VARCHAR2(2 BYTE), 
	"ANNUS" VARCHAR2(2 BYTE), 
	"UPLUS" VARCHAR2(2 BYTE), 
	"OKCB" VARCHAR2(2 BYTE), 
	"LPOINT" VARCHAR2(2 BYTE), 
	"GSNP" VARCHAR2(2 BYTE), 
	"HYOIL" VARCHAR2(2 BYTE), 
	"HAPP" VARCHAR2(2 BYTE), 
	"HBLUEP" VARCHAR2(2 BYTE), 
	"JOONGANG" VARCHAR2(2 BYTE), 
	"HYDM" VARCHAR2(2 BYTE), 
	"HAPPCASH" VARCHAR2(2 BYTE), 
	"BOOKCASH" VARCHAR2(2 BYTE), 
	"CULTCASH" VARCHAR2(2 BYTE), 
	"CULTURENURI" VARCHAR2(2 BYTE), 
	"SAME_USE_PAYMENT" VARCHAR2(10 BYTE), 
	"RADIO_PAYMENT" VARCHAR2(20 BYTE), 
	"CARD_SELECT" VARCHAR2(10 BYTE), 
	"MOVIENM" VARCHAR2(100 BYTE), 
	"PLAYKINDNM" VARCHAR2(100 BYTE), 
	"BRCHNM" VARCHAR2(100 BYTE), 
	"PLAYDE" VARCHAR2(100 BYTE), 
	"DOWNM" VARCHAR2(100 BYTE), 
	"PLAYTIME" VARCHAR2(100 BYTE), 
	"SEAT1" VARCHAR2(50 BYTE), 
	"SEAT2" VARCHAR2(50 BYTE), 
	"SEAT3" VARCHAR2(50 BYTE), 
	"SEAT4" VARCHAR2(50 BYTE), 
	"SEAT5" VARCHAR2(50 BYTE), 
	"SEAT6" VARCHAR2(50 BYTE), 
	"SEAT7" VARCHAR2(50 BYTE), 
	"SEAT8" VARCHAR2(50 BYTE), 
	"ADULTCNT" VARCHAR2(10 BYTE), 
	"YOUNGCNT" VARCHAR2(10 BYTE), 
	"FAVORCNT" VARCHAR2(10 BYTE), 
	"TICKETNUM" VARCHAR2(50 BYTE), 
	"ADULTPRICE" VARCHAR2(100 BYTE), 
	"YOUNGPRICE" VARCHAR2(100 BYTE), 
	"FAVORPRICE" VARCHAR2(100 BYTE), 
	"TOTALPRICE" VARCHAR2(100 BYTE), 
	"THEATER" VARCHAR2(100 BYTE), 
	"TAGNAME" VARCHAR2(100 BYTE), 
	"HANGLE" VARCHAR2(100 BYTE), 
	"MOVIEIMG" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SUZI.FP_PAY
SET DEFINE OFF;
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (1,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','B8',null,null,null,null,null,null,null,'1',null,null,'2022-0523-0','14000','0','0','14000','4관',null,null,null);
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (2,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','D8',null,null,null,null,null,null,null,'1',null,null,'2022-0523-1','14000','0','0','14000','4관',null,'15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (3,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','F9',null,null,null,null,null,null,null,null,'1',null,'2022-0523-2','0','7000','0','7000','4관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (4,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','E5',null,null,null,null,null,null,null,'1',null,null,'2022-0523-3','14000','0','0','14000','4관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (5,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','D4',null,null,null,null,null,null,null,'1',null,null,'2022-0523-4','14000','0','0','14000','4관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (6,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:30~
						11:25','E5',null,null,null,null,null,null,null,'1',null,null,'2022-0523-5','14000','0','0','14000','2관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (7,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','F7',null,null,null,null,null,null,null,null,'1',null,'2022-0523-6','0','7000','0','7000','4관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (8,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','C6',null,null,null,null,null,null,null,'1',null,null,'2022-0523-7','14000','0','0','14000','4관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (9,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','C5',null,null,null,null,null,null,null,'1',null,null,'2022-0523-8','14000','0','0','14000','4관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
Insert into SUZI.FP_PAY (NUM,MEMP,DCOUPON,VIPCPON,MCOUPON,SCOUPON,MGFCARD,BOOKGIFT,CULTGIFT,PAYSGIFT,FRIENDS,ANNUS,UPLUS,OKCB,LPOINT,GSNP,HYOIL,HAPP,HBLUEP,JOONGANG,HYDM,HAPPCASH,BOOKCASH,CULTCASH,CULTURENURI,SAME_USE_PAYMENT,RADIO_PAYMENT,CARD_SELECT,MOVIENM,PLAYKINDNM,BRCHNM,PLAYDE,DOWNM,PLAYTIME,SEAT1,SEAT2,SEAT3,SEAT4,SEAT5,SEAT6,SEAT7,SEAT8,ADULTCNT,YOUNGCNT,FAVORCNT,TICKETNUM,ADULTPRICE,YOUNGPRICE,FAVORPRICE,TOTALPRICE,THEATER,TAGNAME,HANGLE,MOVIEIMG) values (10,'N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','N','off','mobile','00','범죄도시 2','2D','강남','2022.05.23','(월)','09:00~
						10:55','C7',null,null,null,null,null,null,null,'1',null,null,'2022-0523-9','14000','0','0','14000','4관','age-15','15세이상 관람가','4f6aaf4c-eb2b-43f1-a40f-ca782e2d4e0a_xemO2V3dH1nOUPmFAbD1mp2LGFNKpuTf_420.jpg');
--------------------------------------------------------
--  DDL for Index PK_TICKET_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUZI"."PK_TICKET_NUM" ON "SUZI"."FP_PAY" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FP_PAY
--------------------------------------------------------

  ALTER TABLE "SUZI"."FP_PAY" ADD CONSTRAINT "PK_FP_PAY_NUM" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SUZI"."FP_PAY" MODIFY ("NUM" NOT NULL ENABLE);
